#!/bin/sh

# Initialize variables with default values
mode="importmap"
interpreter="mri"
version="latest"
beta_mode=false

# Help function in English
show_help() {
  echo "Usage: moduloproject [-m MODE] [-i INTERPRETER] [-v VERSION] [-b] [-h]"
  echo "  -m MODE         Mode (importmap, esbuild, webpack). Default: importmap"
  echo "  -i INTERPRETER  Interpreter (mri, jruby). Default: mri"
  echo "  -v VERSION      Version. Default: latest"
  echo "  -b              Enable beta mode (uses development branch)"
  echo "  -h              Display this help message"
}

# Parse options
while getopts "m:i:v:bh" opt; do
  case $opt in
    m) mode=$OPTARG ;;
    i) interpreter=$OPTARG ;;
    v) version=$OPTARG ;;
    b) beta_mode=true ;;
    h) show_help; exit 0 ;;
    \?) echo "Invalid option: -$OPTARG" >&2; show_help; exit 1 ;;
  esac
done

# Validate options
if [ "$mode" != "importmap" ] && [ "$mode" != "esbuild" ] && [ "$mode" != "webpack" ]; then
  echo "Unknown mode: $mode" >&2
  show_help
  exit 1
fi

if [ "$interpreter" != "mri" ] && [ "$interpreter" != "jruby" ]; then
  echo "Unknown interpreter: $interpreter" >&2
  show_help
  exit 1
fi

echo "Executing with mode $mode on interpreter $interpreter (version $version)"
if [ "$beta_mode" = true ]; then
  echo "Beta mode enabled: using development branch"
fi

local_project_directory=$(pwd -P)
project_name=${local_project_directory##*/}
docker_project_directory="/$project_name"
git_email=$(git config --get user.email)
git_name=$(git config --get user.name)

echo "Generating project $project_name"

# Set the template URL based on beta mode
if [ "$beta_mode" = true ]; then
  template_url="https://raw.githubusercontent.com/moduloTech/moduloproject/development/template.rb"
else
  template_url="https://raw.githubusercontent.com/moduloTech/moduloproject/master/template.rb"
fi

script='echo "Installing latest version of Rails" && \
    gem install rails --no-document && \
    echo "Installing latest version of Bundler" && \
    gem update --system && \
    echo "Configuring name for default branch of git" && \
    git config --global init.defaultBranch master && \
    echo "Generating new Rails application" && \
    rails new . -d postgresql -m '"$template_url"' $EXTRA_RAILS_ARGS'

test "$interpreter" = "mri" && image="ruby:$version"
test "$interpreter" = "jruby" && image="jruby:$version"

if [ "$mode" != "importmap" ]; then
  extra_rails_args="-j $JAVASCRIPT_MODE -c sass"
else
  extra_rails_args=""
fi

# Add variables for PostgreSQL
postgres_container_name="moduloproject_postgres"
postgres_password="mysecretpassword"

echo "Starting PostgreSQL container"
docker run --name $postgres_container_name -e POSTGRES_PASSWORD=$postgres_password -d postgres:latest

# Wait for PostgreSQL to be ready
echo "Waiting for PostgreSQL to start..."
sleep 10

# Get the IP address of the PostgreSQL container
postgres_ip=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $postgres_container_name)

# Build the database URL
database_url="postgres://postgres:${postgres_password}@${postgres_ip}:5432/postgres"

# Run Docker command
docker run --name moduloproject --pull=always --rm -a STDOUT -ti -w "$docker_project_directory" \
  -v "$local_project_directory":"$docker_project_directory" \
  -e "GIT_AUTHOR_EMAIL=$git_email" -e "GIT_AUTHOR_NAME=$git_name" -e "GIT_COMMITTER_EMAIL=$git_email" -e "GIT_COMMITTER_NAME=$git_name" \
  -e "JAVASCRIPT_MODE=$mode" -e "EXTRA_RAILS_ARGS=$extra_rails_args" \
  -e "DATABASE_URL=$database_url" \
  --network host \
  "$image" bash -c "$script"

# Cleanup: stop and remove PostgreSQL container
echo "Cleanup: stopping PostgreSQL container"
docker stop $postgres_container_name
docker rm $postgres_container_name
