#!/bin/sh

# Script version
SCRIPT_VERSION="1.0"

# Initialize variables with default values
mode="importmap"
interpreter="mri"
version="latest"
beta_mode=false

# Function to update the script
update_script() {
    local url=$1
    local force=$2
    echo "Checking for updates..."

    # Download the new version
    if curl -s "$url" -o "/tmp/moduloproject_new"; then
        # Compare versions
        new_version=$(grep "SCRIPT_VERSION=" "$(which moduloproject)" | cut -d'"' -f2 | grep -v "SCRIPT_VERSION")
        if [ "$new_version" != "$SCRIPT_VERSION" ]; then
            if [ "$force" = true ] || [ "$beta_mode" = true -a "$force" = false ]; then
                read -p "New version $new_version available. Update? (y/n) " -n 1 -r
                echo
                if [[ $REPLY =~ ^[Yy]$ ]]; then
                    echo "Updating script..."
                    if sudo mv "/tmp/moduloproject_new" "/usr/local/bin/moduloproject" && sudo chmod +x "/usr/local/bin/moduloproject"; then
                        echo "Update successful. Please run the script again."
                        exit 0
                    else
                        echo "Update failed. Please try again or update manually."
                        exit 1
                    fi
                fi
            elif [ "$force" = true ]; then
                echo "Forcing update to version $new_version..."
                if sudo mv "/tmp/moduloproject_new" "/usr/local/bin/moduloproject" && sudo chmod +x "/usr/local/bin/moduloproject"; then
                    echo "Forced update successful. Please run the script again."
                    exit 0
                else
                    echo "Forced update failed. Please try again or update manually."
                    exit 1
                fi
            fi
        else
            echo "You are already using the latest version."
        fi
    else
        echo "Failed to check for updates."
    fi
    rm -f "/tmp/moduloproject_new"
}

# Help function in English
show_help() {
  echo "Usage: moduloproject [-m MODE] [-i INTERPRETER] [-r RUBY_VERSION] [-b] [-u] [-h] [-v]"
  echo "  -m MODE         Mode (importmap, esbuild, webpack). Default: importmap"
  echo "  -i INTERPRETER  Interpreter (mri, jruby). Default: mri"
  echo "  -r RUBY_VERSION Ruby version. Default: latest"
  echo "  -b              Enable beta mode (uses development branch)"
  echo "  -u              Force update check"
  echo "  -h              Display this help message"
  echo "  -v              Display script version"
}

# Parse options
while getopts "m:i:r:buhv" opt; do
  case $opt in
    m) mode=$OPTARG ;;
    i) interpreter=$OPTARG ;;
    r) ruby_version=$OPTARG ;;
    b) beta_mode=true ;;
    u) update_script "https://raw.githubusercontent.com/moduloTech/moduloproject/master/moduloproject" true ;;
    h) show_help; exit 0 ;;
    v) echo "moduloproject version $SCRIPT_VERSION"; exit 0 ;;
    \?) echo "Invalid option: -$OPTARG" >&2; show_help; exit 1 ;;
  esac
done

# Check for updates
if [ "$beta_mode" = true ]; then
    update_script "https://raw.githubusercontent.com/moduloTech/moduloproject/development/moduloproject" false
else
    update_script "https://raw.githubusercontent.com/moduloTech/moduloproject/master/moduloproject" true
fi

# Validate options
if [ "$mode" != "importmap" ] && [ "$mode" != "esbuild" ] && [ "$mode" != "webpack" ]; then
  echo "Unknown mode: $mode" >&2
  show_help
  exit 1
fi

if [ "$interpreter" != "mri" ] && [ "$interpreter" != "jruby" ]; then
  echo "Unknown interpreter: $interpreter" >&2
  show_help
  exit 1
fi

echo "Executing with mode $mode on interpreter $interpreter (version $version)"
if [ "$beta_mode" = true ]; then
  echo "Beta mode enabled: using development branch"
fi

local_project_directory=$(pwd -P)
project_name=${local_project_directory##*/}
docker_project_directory="/$project_name"
git_email=$(git config --get user.email)
git_name=$(git config --get user.name)

echo "Generating project $project_name"

# Set the template URL based on beta mode
if [ "$beta_mode" = true ]; then
  template_url="https://raw.githubusercontent.com/moduloTech/moduloproject/development/template.rb"
else
  template_url="https://raw.githubusercontent.com/moduloTech/moduloproject/master/template.rb"
fi

script='echo "Installing latest version of Rails" && \
    gem install rails --no-document && \
    echo "Installing latest version of Bundler" && \
    gem update --system && \
    echo "Configuring name for default branch of git" && \
    git config --global init.defaultBranch master && \
    echo "Generating new Rails application" && \
    rails new . -d postgresql -m '"$template_url"' $EXTRA_RAILS_ARGS'

test "$interpreter" = "mri" && image="ruby:$version"
test "$interpreter" = "jruby" && image="jruby:$version"

if [ "$mode" != "importmap" ]; then
  extra_rails_args="-j $JAVASCRIPT_MODE -c sass"
else
  extra_rails_args=""
fi

# Add variables for PostgreSQL
postgres_container_name="moduloproject_postgres"
postgres_password="mysecretpassword"

echo "Starting PostgreSQL container"
docker run --name $postgres_container_name -e POSTGRES_PASSWORD=$postgres_password -d postgres:latest

# Wait for PostgreSQL to be ready
echo "Waiting for PostgreSQL to start..."
sleep 10

# Get the IP address of the PostgreSQL container
postgres_ip=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $postgres_container_name)

# Build the database URL
database_url="postgres://postgres:${postgres_password}@${postgres_ip}:5432/postgres"

# Run Docker command
docker run --name moduloproject --pull=always --rm -a STDOUT -ti -w "$docker_project_directory" \
  -v "$local_project_directory":"$docker_project_directory" \
  -e "GIT_AUTHOR_EMAIL=$git_email" -e "GIT_AUTHOR_NAME=$git_name" -e "GIT_COMMITTER_EMAIL=$git_email" -e "GIT_COMMITTER_NAME=$git_name" \
  -e "JAVASCRIPT_MODE=$mode" -e "EXTRA_RAILS_ARGS=$extra_rails_args" -e "MODULORAILS_BETA_MODE=$beta_mode" \
  -e "DATABASE_URL=$database_url" \
  --network host \
  "$image" bash -c "$script"

# Cleanup: stop and remove PostgreSQL container
echo "Cleanup: stopping PostgreSQL container"
docker stop $postgres_container_name
docker rm $postgres_container_name
