# frozen_string_literal: true

# Auto-generated by script/generate_integration_specs.rb
# Combination: rails72_ruby33_sqlite3_vue_sidekiq_redis_redis

require_relative '../spec_helper'

RSpec.describe 'moduloproject new: rails72_ruby33_sqlite3_vue_sidekiq_redis_redis', :integration do
  combination = IntegrationTests::Matrix::Combination.new(
    rails: '7.2',
    ruby: '3.3',
    database: 'sqlite3',
    frontend: 'vue',
    active_job: 'sidekiq',
    action_cable: 'redis',
    rails_cache: 'redis'
  )

  before(:all) do
    IntegrationTests::DockerGuard.skip_unless_docker!(self)

    @workspace = IntegrationTests::ProjectWorkspace.create(combination)
    @project_root = IntegrationTests::ProjectWorkspace.project_root(@workspace, combination)

    Dir.chdir(@workspace) do
      $stdout = StringIO.new
      Moduloproject::Commands::New.new(combination.app_name, combination.options_hash).execute
    ensure
      $stdout = STDOUT
    end
  end

  after(:all) do
    IntegrationTests::ProjectWorkspace.cleanup(@workspace) if @workspace
  end

  let(:project_root) { @project_root }

  it_behaves_like 'rails boilerplate', combination
  it_behaves_like 'docker files', combination
  it_behaves_like 'devcontainer files', combination
  it_behaves_like 'gitlab ci files', combination
  it_behaves_like 'git hooks files', combination
  it_behaves_like 'claude code files', combination
  it_behaves_like 'config files', combination
  it_behaves_like 'tracking file', combination
  it_behaves_like 'gemfile content', combination
  it_behaves_like 'application.rb content', combination
  it_behaves_like 'production.rb content', combination
  it_behaves_like 'solid cleanup', combination
  it_behaves_like 'git repository', combination
  it_behaves_like 'vite files', combination
  it_behaves_like 'modulorails files', combination
end
