#!/usr/bin/env ruby
# frozen_string_literal: true

# Generates integration spec files (one per combination) in
# spec/integration/combinations/
#
# Usage: ruby script/generate_integration_specs.rb

require 'fileutils'
require_relative '../spec/integration/support/matrix'

OUTPUT_DIR = File.expand_path('../spec/integration/combinations', __dir__)

SHARED_EXAMPLES = [
  'rails boilerplate',
  'docker files',
  'devcontainer files',
  'gitlab ci files',
  'git hooks files',
  'claude code files',
  'config files',
  'tracking file',
  'gemfile content',
  'application.rb content',
  'production.rb content',
  'solid cleanup',
  'git repository',
  'vite files',
  'modulorails files'
].freeze

def generate_spec(combination)
  includes = SHARED_EXAMPLES.map { |name| "  include_examples '#{name}', combination" }.join("\n")

  <<~RUBY
    # frozen_string_literal: true

    # Auto-generated by script/generate_integration_specs.rb
    # Combination: #{combination.label}

    require_relative '../spec_helper'

    RSpec.describe 'moduloproject new: #{combination.label}', :integration do
      combination = IntegrationTests::Matrix::Combination.new(
        rails: '#{combination.rails}',
        ruby: '#{combination.ruby}',
        database: '#{combination.database}',
        frontend: '#{combination.frontend}',
        active_job: '#{combination.active_job}',
        action_cable: '#{combination.action_cable}',
        rails_cache: '#{combination.rails_cache}'
      )

      before(:all) do
        IntegrationTests::DockerGuard.skip_unless_docker!(self)

        @workspace = IntegrationTests::ProjectWorkspace.create(combination)
        @project_root = IntegrationTests::ProjectWorkspace.project_root(@workspace, combination)

        Dir.chdir(@workspace) do
          $stdout = StringIO.new
          Moduloproject::Commands::New.new(combination.app_name, combination.options_hash).execute
        ensure
          $stdout = STDOUT
        end
      end

      after(:all) do
        IntegrationTests::ProjectWorkspace.cleanup(@workspace) if @workspace
      end

      let(:project_root) { @project_root }

    #{includes}
    end
  RUBY
end

# Clean existing files
FileUtils.rm_rf(OUTPUT_DIR)
FileUtils.mkdir_p(OUTPUT_DIR)

combinations = IntegrationTests::Matrix.all_combinations

combinations.each do |combo|
  file_path = File.join(OUTPUT_DIR, "#{combo.label}_spec.rb")
  File.write(file_path, generate_spec(combo))
end

puts "Generated #{combinations.size} integration spec files in #{OUTPUT_DIR}"
