# frozen_string_literal: true

RSpec.shared_examples 'vite files' do |combination|
  next unless combination.frontend == 'vue'

  describe 'Vite files (Vue frontend)' do
    it 'creates bin/vite as a Bundler binstub' do
      path = File.join(project_root, 'bin/vite')
      expect(File.exist?(path)).to be true

      content = File.read(path)
      expect(content).to include('#!/usr/bin/env ruby')
      expect(content).to include('frozen_string_literal: true')
      expect(content).to include('This file was generated by Bundler')
      expect(content).to include('ENV["BUNDLE_GEMFILE"] ||= File.expand_path("../Gemfile", __dir__)')
      expect(content).to include('require "bundler/setup"')
      expect(content).to include('Gem.bin_path("vite_ruby", "vite")')
    end

    it 'creates config/vite.json with valid JSON' do
      path = File.join(project_root, 'config/vite.json')
      expect(File.exist?(path)).to be true
      expect(path).to have_valid_json
    end

    it 'creates Procfile.dev' do
      procfile = File.join(project_root, 'Procfile.dev')

      expect(File.exist?(procfile)).to be true
      expect(File.read(procfile)).to include('vite')
    end

    it 'creates bin/dev' do
      bin_dev = File.join(project_root, 'bin/dev')

      expect(File.exist?(bin_dev)).to be true
      expect(File.read(bin_dev)).to include('foreman')
    end

    describe 'package.json content' do
      let(:package_json) { JSON.parse(File.read(File.join(project_root, 'package.json'))) }

      it 'has required dependencies' do
        deps = package_json['dependencies'] || {}
        %w[
          @vueuse/core
          vue
          vue-i18n
          vue-multiselect
          vue-router
        ].each do |dep|
          expect(deps).to have_key(dep), "expected dependency '#{dep}' in package.json"
        end
      end

      it 'has required devDependencies' do
        dev_deps = package_json['devDependencies'] || {}
        %w[
          @eslint/js
          @testing-library/vue
          @vitest/coverage-v8
          @vue/test-utils
          eslint
          eslint-plugin-vue
          happy-dom
          vite
          vite-plugin-ruby
          vite-svg-loader
          vitest
        ].each do |dep|
          expect(dev_deps).to have_key(dep), "expected devDependency '#{dep}' in package.json"
        end
      end

      it 'has required scripts' do
        scripts = package_json['scripts'] || {}
        expected_scripts = {
          'build' => 'bin/vite build',
          'dev' => 'bin/vite',
          'lint' => 'npx eslint app/frontend',
          'test' => 'vitest run',
          'test:watch' => 'vitest',
          'test:coverage' => 'vitest run --coverage'
        }
        expected_scripts.each do |name, command|
          expect(scripts[name]).to eq(command), "expected script '#{name}' to be '#{command}', got '#{scripts[name]}'"
        end
      end
    end
  end
end
